import type { BusinessCaseInput, ReplacementVehicle } from "@/engine/types";

export function createId(): string {
  return crypto.randomUUID();
}

export const VEHICLE_PRESETS: Omit<ReplacementVehicle, "id">[] = [
  {
    name: "BYD Shark 6",
    manufacturer: "BYD",
    price: 960000,
    deposit: 0,
    interestRate: 10,
    financeTermMonths: 72,
    fuelType: "phev",
    batterySizeKwh: 29.6,
    fuelConsumption: 7.5,
    energyConsumption: 22,
    warrantyYears: 6,
    batteryWarrantyYears: 8,
    maintenance: 8000,
    insurance: 18000,
    expectedResale: 450000,
  },
  {
    name: "BYD Dolphin",
    manufacturer: "BYD",
    price: 520000,
    deposit: 0,
    interestRate: 10,
    financeTermMonths: 72,
    fuelType: "electric",
    batterySizeKwh: 60.4,
    fuelConsumption: 0,
    energyConsumption: 15,
    warrantyYears: 6,
    batteryWarrantyYears: 8,
    maintenance: 5000,
    insurance: 14000,
    expectedResale: 280000,
  },
  {
    name: "iCAUR V23",
    manufacturer: "iCAUR",
    price: 650000,
    deposit: 0,
    interestRate: 10,
    financeTermMonths: 72,
    fuelType: "electric",
    batterySizeKwh: 81,
    fuelConsumption: 0,
    energyConsumption: 18,
    warrantyYears: 5,
    batteryWarrantyYears: 8,
    maintenance: 6000,
    insurance: 16000,
    expectedResale: 350000,
  },
  {
    name: "Tesla Model 3",
    manufacturer: "Tesla",
    price: 850000,
    deposit: 0,
    interestRate: 10,
    financeTermMonths: 72,
    fuelType: "electric",
    batterySizeKwh: 75,
    fuelConsumption: 0,
    energyConsumption: 14,
    warrantyYears: 4,
    batteryWarrantyYears: 8,
    maintenance: 4000,
    insurance: 20000,
    expectedResale: 420000,
  },
  {
    name: "Toyota Hilux GR-S",
    manufacturer: "Toyota",
    price: 980000,
    deposit: 0,
    interestRate: 11,
    financeTermMonths: 72,
    fuelType: "diesel",
    batterySizeKwh: 0,
    fuelConsumption: 9.5,
    energyConsumption: 0,
    warrantyYears: 3,
    batteryWarrantyYears: 0,
    maintenance: 15000,
    insurance: 22000,
    expectedResale: 550000,
  },
  {
    name: "Ford Ranger Wildtrak",
    manufacturer: "Ford",
    price: 920000,
    deposit: 0,
    interestRate: 11,
    financeTermMonths: 72,
    fuelType: "diesel",
    batterySizeKwh: 0,
    fuelConsumption: 8.5,
    energyConsumption: 0,
    warrantyYears: 4,
    batteryWarrantyYears: 0,
    maintenance: 14000,
    insurance: 21000,
    expectedResale: 520000,
  },
];

export function createDefaultBusinessCase(): BusinessCaseInput {
  const sharkId = createId();
  return {
    type: "fleet-ev",
    current: {
      manufacturer: "Ford",
      model: "Wildtrak Bi-Turbo",
      year: 2021,
      mileage: 85000,
      currentValue: 620000,
      outstandingFinance: 280000,
      monthlyInstalment: 10450,
      fuelType: "diesel",
      fuelConsumption: 9.2,
      insurance: 24000,
      maintenance: 18000,
      tyres: 12000,
      licence: 1200,
      expectedAnnualRepairs: 15000,
      tradeInValue: 620000,
      residualValue: 380000,
      hasTurbo: true,
      hasDpf: true,
      warrantyExpired: true,
    },
    replacements: [
      {
        id: sharkId,
        ...VEHICLE_PRESETS[0],
      },
    ],
    tradeIn: {
      additionalCashDeposit: 200000,
    },
    assumptions: {
      dailyDistanceKm: 50,
      fuelPricePerLitre: 23.5,
      electricityTariff: 2.85,
      peakTariff: 4.2,
      offPeakTariff: 1.8,
      annualKmGrowth: 2,
    },
    solar: {
      systemSizeKw: 8,
      batterySizeKwh: 10,
      solarChargingPercent: 70,
      gridChargingPercent: 30,
      electricityTariff: 2.85,
      peakTariff: 4.2,
      offPeakTariff: 1.8,
    },
    selectedReplacementId: sharkId,
  };
}

export const SCENARIO_TAGS = [
  "Business Use",
  "Personal Use",
  "No Solar",
  "95% Solar",
  "Fleet",
  "Family Vehicle",
  "120 km/day",
];
